### ISSUE TITLE
Possible to map multiple repetitive column as object list?

### ISSUE THREAD

**Issue by hendryang** [vaa25/poiji2#1]
Hi Vaa25,

Accidentally stumbled upon this repo!

Any idea how to I handle such scenario?

Given I have table below , ( I can't merge cell with MD , but assume Person 1 is merge cell for column B,C,D. same goes to Person 2 and Person 3)

This is basically a list of 3 Person objects within a single table, is there a way to handle such scenario that we can map those 3 persons to List<Person> ? Thank you

ps. also i notice, `headerCount(...)` option to support multiple header isn't available in poiji2

| Data | Person 1 || | Person 2| | | Person 3 | |  |
| ---- | -------- | -------- | -------- | -------- | -------- | -------- |-------- | -------- | -------- |
|| Name | Gender   | Age      | Name     | Gender | Age | Name | Gender | Age |
| 1    | test     | male     | 10       | gogo | female | 20 |  |  |  |
| 2    | abc      | male     | 30       | vivi | female | 40 | vava | female | 40 |

**Comment by vaa25** [comment]
@hendryang Hi! Thank you for feedback! headerCount is added in v1.2.2
Also your requirements are implemented in v1.3.0.

See [ReadExcelListTest](https://github.com/vaa25/poiji2/blob/v1.3.0/src/test/java/com/poiji/deserialize/ReadExcelListTest.java) to understand how to implement code. Your example table is used as test data. ([ListElement](https://github.com/vaa25/poiji2/blob/v1.3.0/src/test/java/com/poiji/deserialize/model/ListElement.java), [ListEntity](https://github.com/vaa25/poiji2/blob/v1.3.0/src/test/java/com/poiji/deserialize/model/ListEntity.java))

Feel free to tell if you find any bugs.
